FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev

COPY . .

RUN apk add --no-cache docker-cli

EXPOSE 5000

CMD ["npm", "start"]

# docker buildx build --platform linux/amd64,linux/arm64 -f dockerFile -t bhandekunal16/docker-dashboard:0.0.2 --push .

# docker tag docker-dashboard:0.0.1 bhandekunal16/docker-dashboard:0.0.1

# docker push bhandekunal16/docker-dashboard:0.0.1

# docker run -d --name docker-dashboard --restart unless-stopped -p 5000:5000 -v /var/run/docker.sock:/var/run/docker.sock -e DOCKER_HOST=unix:///var/run/docker.sock bhandekunal16/docker-dashboard:0.0.1

# docker run -d --name docker-dashboard --restart unless-stopped -p 5000:5000 -v /var/run/docker.sock:/var/run/docker.sock -e DOCKER_HOST=unix:///var/run/docker.sock docker-dashboard:0.0.1